apiVersion: apps/v1
kind: Deployment
metadata:
  name: jde
spec:
  selector:
    matchLabels:
      app: jde
  template:
    metadata:
      labels:
        app: jde
    spec:
      serviceAccountName: jde-service-account
      containers:
      - name: jde
        image: kdvolder/remote-java-dev-env
        env:
        - name: AUTHORIZED_KEY
          valueFrom:
            secretKeyRef:
              name: ssh-secret
              key: AUTHORIZED_KEY
        resources:
           limits:
             memory: "4000Mi"
             cpu: "2000m"
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: jde
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jde
  type: LoadBalancer


